AWSTemplateFormatVersion: “2010-09-09”
Description: Create ECS ALB

# ------------------------------------------------------------#
#  Parameters
# ------------------------------------------------------------#
Parameters:
  ECSTaskRole:
    Type: String
  ECSExecutionRole:
    Type: String
  ECSServiceName:
    Type: String
    Default: “service”
  ECSALBName:
    Type: String
    Default: “lb”
  ECSTaskName:
    Type: String
    Default: “task”
  ECSClusterName:
    Type: String
    Default: “cluster”
  ECSTargetGroupName:
    Type: String
    Default: “tg”
  ECSCount:
    Type: Number
    Default: “01"
  ECSTaskCPUUnit:
    Type: String
    Default: “1024”
    AllowedValues: [256, 512, 1024, 2048]
  ECSTaskMemory:
    Type: String
    Default: “2048"
    AllowedValues: [512, 1024, 2048, 4096]
  ECSTaskPort:
    Type: String
    Default: “3003”
    AllowedValues: [3000, 300]
  VpcId:
    Type: String
    Default: “vpc-"
  FrontSecurityGroupId:
    Type: String
    Default: “sg-
  FrontSubnetId1:
    Type: String
    Default: “subnet-"
  FrontSubnetId2:
    Type: String
    Default: “subnet-
  AppSecurityGroupId:
    Type: String
    Default: “sg-
  AppSubnetId1:
    Type: String
    Default: “subnet-"
  AppSubnetId2:
    Type: String
    Default: “subnet-"

# ------------------------------------------------------------#
#   Resources
# ------------------------------------------------------------#
Resources:
  # ------------------------------------------------------------#
  #  ECS
  # ------------------------------------------------------------#
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub “${ECSContainerName}-ecs-${ECSTaskName}”
      Cpu: !Ref ECSTaskCPUUnit
      Memory: !Ref ECSTaskMemory
      TaskRoleArn: !Ref ECSTaskRole
      ExecutionRoleArn: !Ref ECSExecutionRole
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: !Sub “${ECSContainerName}”
          Essential: true
          Image: !Sub “${AWS::AccountId}.dkr.ecr.${AWS::Region}.http://amazonaws.com/ecs/ecs/$http://amazonaws.com/ecs/ecs/${ECSContainerName}”
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub “/ecs/ecs”
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          PortMappings:
            - ContainerPort: !Ref ECSTaskPort
              HostPort: !Ref ECSTaskPort
              Protocol: tcp
          Environment:
            - Name: PORT
              Value: !Ref ECSTaskPort
            - Name: HOST_PORT
              Value: !Ref ECSTaskPort
  ECSCloudwatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub “/ecs/ecs”

  # ------------------------------------------------------------#
  #  ALB
  # ------------------------------------------------------------#
