AWSTemplateFormatVersion: "2010-09-09"
Description: Create ECS BlueGreen CodeDeploy Role

# ------------------------------------------------------------#
#   Parameters
# ------------------------------------------------------------#
Parameters:
  ServicePrefix:
    Type: String
    Default: "example"
  EnvPrefix:
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "stg"
      - "prd"

# ------------------------------------------------------------#
#   Resources
# ------------------------------------------------------------#
Resources:
  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ServicePrefix}-${EnvPrefix}-deploy-role"
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: http://codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS
