AWSTemplateFormatVersion: "2010-09-09"
Description: Create ECR

# ------------------------------------------------------------#
#   Parameters
# ------------------------------------------------------------#
Parameters:
  Prefix:
    Type: String
    Default: "example"
    AllowedValues:
      - "example"
  ECSContainerName:
    Type: String
    Default: "example"
    AllowedValues:
      - "example"

# ------------------------------------------------------------#
#   Resources
# ------------------------------------------------------------#
Resources:
  # ------------------------------------------------------------#
  #  ECR
  # ------------------------------------------------------------#
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${Prefix}/${ECSContainerName}
