AWSTemplateFormatVersion: “2010-09-09”
Description: Create ECS Cluster

# ------------------------------------------------------------#
#   Parameters
# ------------------------------------------------------------#
Parameters:
  ServicePrefix:
    Type: String
    Default: "example"
  EnvPrefix:
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "stg"
      - "prd"

# ------------------------------------------------------------#
#   Resources
# ------------------------------------------------------------#
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${ServicePrefix}-${EnvPrefix}-ecs-cluster"
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

# ------------------------------------------------------------#
#   Outputs
# ------------------------------------------------------------#
Outputs:
  ECSCluster:
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${ServicePrefix}-${EnvPrefix}-ecs-cluster"
