AWSTemplateFormatVersion: "2010-09-09"
Description: Create Aurora

# ------------------------------------------------------------#
#   Parameters
# ------------------------------------------------------------#
Parameters:
  ServicePrefix:
    Type: String
    Default: "example"
  EnvPrefix:
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "stg"
      - "prd"
  DBMasterUserName:
    Type: String
    Default: admin
  DBMasterUserPassword:
    Type: String
  DBEngine:
    Type: String
    Default: aurora-mysql
  DBEngineVersion:
    Type: String
    Default: 5.7
  DBInstanceClass:
    Type: String
    Default: db.t3.small

# ------------------------------------------------------------#
#  Resources
# ------------------------------------------------------------#
Resources:
  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Sub "${ServicePrefix}-${EnvPrefix}-aurora-cluster"
      DeletionProtection: true
      DBSubnetGroupName: !Ref AuroraSubnetGroup
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      MasterUsername: !Ref DBMasterUserName
      MasterUserPassword: !Ref DBMasterUserPassword
      VpcSecurityGroupIds:
        - Fn::ImportValue: !Sub "${ServicePrefix}-${EnvPrefix}-data-sg"
      EnableCloudwatchLogsExports:
        - audit
        - error
        - general
        - slowquery

  AuroraInstanceA:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceIdentifier: !Sub "${ServicePrefix}-${EnvPrefix}-aurora-writer-01"
      DBInstanceClass: !Ref DBInstanceClass
      Engine: !Ref DBEngine

  AuroraSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub subnetgroup
      SubnetIds:
        - Fn::ImportValue: !Sub "${ServicePrefix}-${EnvPrefix}-data-subnet-a"
        - Fn::ImportValue: !Sub "${ServicePrefix}-${EnvPrefix}-data-subnet-c"
